# Site settings
title: Problemas CEP UCSP
email: raul.gallegos@ucsp.edu.pe
description: > # this means to ignore newlines until "baseurl:"
  Base de Datos de Problemas para el Concurso Escolar de Programaci√≥n UCSP,
  para entrenamiento de los alumnos y tutores.
url: "http://cs.ucsp.edu.pe" # the base hostname & protocol for your site
baseurl: "/aprende"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
